import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv
from typing import Dict, Any

load_dotenv()

def send_email_with_attachment(to_email: str, subject: str, body: str, attachment_path: str):
    """
    Sends an email with a file attachment using SMTP settings from environment variables.
    """
    smtp_server = os.getenv("SMTP_SERVER")
    smtp_port = os.getenv("SMTP_PORT")
    smtp_user = os.getenv("SMTP_USERNAME")
    smtp_password = os.getenv("SMTP_PASSWORD")
    email_from = os.getenv("EMAIL_FROM", smtp_user)

    if not all([smtp_server, smtp_port, smtp_user, smtp_password]):
        raise ValueError("Missing SMTP configuration in environment variables.")

    # Create message
    msg = MIMEMultipart()
    msg['From'] = email_from
    msg['To'] = to_email
    msg['Subject'] = subject

    msg.attach(MIMEText(body, 'plain'))

    # Attach file
    if attachment_path and os.path.exists(attachment_path):
        filename = os.path.basename(attachment_path)
        with open(attachment_path, "rb") as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', f"attachment; filename= {filename}")
            msg.attach(part)
    elif attachment_path:
        print(f"Warning: Attachment path {attachment_path} does not exist.")

    # Send email
    print(f"Connecting to SMTP server {smtp_server}:{smtp_port}...")
    try:
        # Add a 30 second timeout to avoid hanging the UI
        server = smtplib.SMTP(smtp_server, int(smtp_port), timeout=30)
        server.set_debuglevel(1) # Enable debug output for terminal
        server.starttls()
        server.login(smtp_user, smtp_password)
        server.send_message(msg)
        server.quit()
        print("Email sent successfully!")
        return True
    except Exception as e:
        print(f"Error sending email: {str(e)}")
        raise e


def send_analysis_email(to_email: str, result: Dict[str, Any], include_charts: bool = True) -> bool:
    """
    Send analysis results via email.
    
    Args:
        to_email: Recipient email address
        result: Analysis result dictionary containing recommendation, explanation, etc.
        include_charts: Whether to include chart attachments (not implemented yet)
    
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    try:
        # Extract recommendation details
        recommendation = result.get('recommendation', {})
        location = recommendation.get('best_location', 'N/A')
        borough = recommendation.get('borough', 'N/A')
        score = recommendation.get('score', 0)
        confidence = recommendation.get('confidence', 'N/A')
        
        explanation = result.get('explanation', 'No explanation available')
        critic_feedback = result.get('critic_feedback', 'No feedback available')
        iterations = result.get('iterations', 0)
        
        # Create email subject
        subject = f"UrbanSpot AI Analysis: {location}, {borough}"
        
        # Create email body
        body = f"""
UrbanSpot AI - Business Location Analysis Report
{'='*60}

RECOMMENDED LOCATION
Location: {location}
Borough: {borough}
Score: {score:.3f}
Confidence: {confidence}
Analysis Iterations: {iterations}

{'='*60}

ANALYSIS EXPLANATION
{explanation}

{'='*60}

CRITIC AGENT FEEDBACK
{critic_feedback}

{'='*60}

This analysis was generated by UrbanSpot AI, a multi-agent system
for NYC business location intelligence.

For more details, please refer to the attached CSV report (if available).

---
UrbanSpot AI
Multi-Agent NYC Business Location Intelligence
"""
        
        # Get CSV attachment path if available
        attachment_path = None
        artifacts = result.get('artifacts', {})
        csv_path = artifacts.get('csv')
        
        if csv_path and os.path.exists(csv_path):
            attachment_path = csv_path
        
        # Send email
        if attachment_path:
            return send_email_with_attachment(
                to_email=to_email,
                subject=subject,
                body=body,
                attachment_path=attachment_path
            )
        else:
            # Send email without attachment
            smtp_server = os.getenv("SMTP_SERVER")
            smtp_port = os.getenv("SMTP_PORT")
            smtp_user = os.getenv("SMTP_USERNAME")
            smtp_password = os.getenv("SMTP_PASSWORD")
            email_from = os.getenv("EMAIL_FROM", smtp_user)
            
            if not all([smtp_server, smtp_port, smtp_user, smtp_password]):
                raise ValueError("Missing SMTP configuration in environment variables.")
            
            msg = MIMEMultipart()
            msg['From'] = email_from
            msg['To'] = to_email
            msg['Subject'] = subject
            msg.attach(MIMEText(body, 'plain'))
            
            server = smtplib.SMTP(smtp_server, int(smtp_port), timeout=30)
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
            server.quit()
            
            print(f"Email sent successfully to {to_email}")
            return True
            
    except Exception as e:
        print(f"Error sending analysis email: {str(e)}")
        import traceback
        traceback.print_exc()
        return False


# For testing
if __name__ == "__main__":
    print("Testing email service...")
    print(f"SMTP Server: {os.getenv('SMTP_SERVER')}")
    print(f"SMTP Username: {os.getenv('SMTP_USERNAME')}")
    print(f"Email From: {os.getenv('EMAIL_FROM')}")
    
    # Test data
    test_result = {
        'recommendation': {
            'best_location': 'SoHo',
            'borough': 'Manhattan',
            'score': 0.892,
            'confidence': 'high'
        },
        'explanation': 'This is a test analysis explanation.',
        'critic_feedback': 'This is test critic feedback.',
        'iterations': 3
    }
    
    test_email = input("Enter test email address (or press Enter to skip): ").strip()
    if test_email:
        success = send_analysis_email(test_email, test_result)
        if success:
            print("✅ Test email sent successfully!")
        else:
            print("❌ Test email failed!")
    else:
        print("Test skipped.")
